[addresses]
emojicoin_dot_fun = "_"
# emojicoin_dot_fun = "0x5df39f893dcbb17631cff37a0b7b848d0397deb2ec23228213fd1245510aedd9"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"

subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
coin_factory = "0xaaaa"
emojicoin_dot_fun = "0xc0de"    
# coin_factory = "0x5df39f893dcbb17631cff37a0b7b848d0397deb2ec23228213fd1245510aedd9"
# emojicoin_dot_fun = "0x5df39f893dcbb17631cff37a0b7b848d0397deb2ec23228213fd1245510aedd9"

[dev-dependencies.BlackCatCoinFactory]
local = "../test_coin_factories/black_cat"

[dev-dependencies.BlackHeartCoinFactory]
local = "../test_coin_factories/black_heart"

[dev-dependencies.EmojicoinDotFunCoinFactory]
local = "../coin_factory"

[dev-dependencies.YellowHeartCoinFactory]
local = "../test_coin_factories/yellow_heart"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "EmojicoinDotFun"
upgrade_policy = "immutable"
version = "1.0.1"
