[addresses]
emojicoin_dot_fun = "_"
# emojicoin_dot_fun = "0xb066504f60719b6c53714c7a8d06a6ee6bb1a79994a2e53175c3ffb7b6ce7e99"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"

subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
coin_factory = "0xaaaa"
emojicoin_dot_fun = "0xc0de"    

[dev-dependencies.BlackCatCoinFactory]
local = "../test_coin_factories/black_cat"

[dev-dependencies.BlackHeartCoinFactory]
local = "../test_coin_factories/black_heart"

[dev-dependencies.EmojicoinDotFunCoinFactory]
local = "../coin_factory"

[dev-dependencies.YellowHeartCoinFactory]
local = "../test_coin_factories/yellow_heart"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "EmojicoinDotFun"
upgrade_policy = "immutable"
version = "1.0.1"
