[addresses]
black_cat_market = "0x44271bf1b1f9945a0c3e0d9a14c7e7d6df07472045d9d395cc4858951549f89"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "BlackCatCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
