[addresses]
black_cat_market = "0xdeff86f3b38ec5f2668729a2df725d1f5ab03529e14ebba5d2ddfc36abaf23ca"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "BlackCatCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
