[addresses]
yellow_heart_market = "0xa0970bfd8f24eb4fe92a4f9980bf87b2c5594057d6942be5bbd5ee5ba6c20151"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "YellowHeartCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
