[addresses]
yellow_heart_market = "0xcbd82a44ed777632f21e0100693f81cce73e685ec1d586408d8e86b95d2821aa"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "YellowHeartCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
