[addresses]
black_heart_market = "0x3d3dc9690e20dbb0de5d1a3522c11b33f4296e05242cd3948ad6d09989420eb6"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "BlackHeartCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
