[addresses]
black_heart_market = "0xedf96c2c141657d311170c3681d917e1534c6f14f2efa00de2a9a5da60d5b0c0"

[dev-dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[package]
name = "BlackHeartCoinFactory"
upgrade_policy = "immutable"
version = "1.0.0"
